defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5

local: &local
  <<: *defaults
  username: root
  password: password
  socket: /tmp/mysql.sock

development:
  <<: *local
  database: hundred_best_days_development

test:
  <<: *local
  database: hundred_best_days_test

#production:
  #<<: *defaults
  #database: hundred_best_days_production
